import type { NextPage } from "next";
import Head from "next/head";

import { useMicroPostsQuery } from "generated/graphql";

const Home: NextPage = () => {
  const { data, loading, error } = useMicroPostsQuery();

  if (loading) {
    return <p>loading</p>;
  }

  if (!data || error) {
    return <p>error</p>;
  }

  const microPosts = data.microPosts;

  console.log(microPosts);

  return (
    <div>
      <Head>
        <title>Oscar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello</h1>
      </main>
    </div>
  );
};

export default Home;
